INSERT INTO `empresa_ofertas_trabajos`
(`IDEmpresa`, `IDPais`, `IDDepartamento`, `IDCategoria`, `IDDesempenado`, `Plaza`, `Descripcion`, `Vacante`,
 `TipoContratacion`, `Genero`, `EdadMenor`, `EdadMayor`, `SalarioMinimo`, `SalarioMaximo`, `Vihiculo`, `TipoVehiculo`,
 `Experiencia`, `IDAreaExperiencia`, `Expira`, `FechaPublicacion`, `Estado`)
VALUES
    (2, 1, 1, 9, 141, 'Desarrollador Full Stack',
     '<p>Estamos buscando un Desarrollador Full Stack con experiencia en el desarrollo de aplicaciones web y móviles, tanto en frontend como en backend. El candidato debe tener conocimientos sólidos en JavaScript, Node.js, React, y bases de datos SQL/NoSQL. Será responsable de diseñar y construir soluciones escalables y eficientes.</p>',
     2, 'Disponibilidad completa', 'Indiferente', 25, 45, 1500, 2500, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Ingeniero de Software',
     '<p>Buscamos un Ingeniero de Software para desarrollar sistemas y aplicaciones web a gran escala. Se requiere experiencia en el diseño de arquitecturas robustas y escalables.</p>',
     3, 'Disponibilidad completa', 'Indiferente', 27, 45, 1800, 2600, 'No requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Administrador de Base de Datos',
     '<p>Se necesita un Administrador de Base de Datos con experiencia en SQL y NoSQL para gestionar bases de datos críticas y garantizar su disponibilidad y rendimiento.</p>',
     1, 'Disponibilidad completa', 'Indiferente', 30, 50, 1700, 2400, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Desarrollador Frontend',
     '<p>Estamos buscando un Desarrollador Frontend con experiencia en frameworks modernos como React y Angular para trabajar en aplicaciones web interactivas y atractivas.</p>',
     2, 'Disponibilidad completa', 'Indiferente', 24, 40, 1400, 2200, 'No requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Analista de Sistemas',
     '<p>Se necesita un Analista de Sistemas con experiencia en la recolección de requisitos y diseño de soluciones para optimizar procesos empresariales.</p>',
     2, 'Disponibilidad completa', 'Indiferente', 28, 45, 1600, 2300, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Especialista DevOps',
     '<p>Buscamos un Especialista DevOps con experiencia en integración continua, despliegue continuo (CI/CD) y administración de servidores en la nube.</p>',
     1, 'Disponibilidad completa', 'Indiferente', 30, 50, 2000, 3000, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Desarrollador Backend',
     '<p>Se necesita un Desarrollador Backend con experiencia en Node.js y bases de datos para desarrollar APIs robustas y escalables.</p>',
     2, 'Disponibilidad completa', 'Indiferente', 26, 45, 1600, 2500, 'No requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Ingeniero en Seguridad Informática',
     '<p>Se busca un Ingeniero en Seguridad Informática con experiencia en la identificación de vulnerabilidades y protección de redes.</p>',
     1, 'Disponibilidad completa', 'Indiferente', 29, 50, 2100, 3200, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Gerente de TI',
     '<p>Estamos buscando un Gerente de TI para liderar equipos y gestionar proyectos tecnológicos de gran envergadura.</p>',
     1, 'Disponibilidad completa', 'Indiferente', 35, 55, 3000, 4500, 'No requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo'),
    (2, 1, 1, 9, 141, 'Consultor SAP',
     '<p>Buscamos un Consultor SAP con experiencia en módulos de finanzas y logística para liderar proyectos de implementación en clientes.</p>',
     1, 'Disponibilidad completa', 'Indiferente', 30, 50, 2500, 4000, 'Requerido', 'Ninguno', 'Si', 7, '2024-11-02', '2024-09-30', 'Activo');

