INSERT INTO soporte_paises_departamento (IDPais, Nombre)
VALUES (45, 'Amazonas'),
       (45, 'Ancash'),
       (45, 'Apurímac'),
       (45, 'Arequipa'),
       (45, 'Ayacucho'),
       (45, 'Cajamarca'),
       (45, 'Callao'),
       (45, 'Cusco'),
       (45, 'Huancavelica'),
       (45, 'Huánuco'),
       (45, 'Ica'),
       (45, 'Junín'),
       (45, 'La Libertad'),
       (45, 'Lambayeque'),
       (45, 'Lima'),
       (45, 'Loreto'),
       (45, 'Madre de Dios'),
       (45, 'Moquegua'),
       (45, 'Pasco'),
       (45, 'Piura'),
       (45, 'Puno'),
       (45, 'San Martín'),
       (45, 'Tacna'),
       (45, 'Tumbes'),
       (45, 'Ucayali');
